'use server';
/**
 * @fileOverview This file defines a Genkit flow for filtering podcast transcripts
 * based on user interests, summarizing relevant content, and identifying
 * key highlights with approximate timings and hook captions.
 *
 * - podcastTranscriptFilteringAndSummarization - The main function to initiate the process.
 * - PodcastTranscriptFilteringAndSummarizationInput - The input type for the flow.
 * - PodcastTranscriptFilteringAndSummarizationOutput - The output type for the flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const PodcastTranscriptFilteringAndSummarizationInputSchema = z.object({
  transcript: z.string().describe('The full text transcript of the podcast episode.'),
  interests: z.array(z.string()).describe('A JSON array of user interests to filter the podcast by.'),
});
export type PodcastTranscriptFilteringAndSummarizationInput = z.infer<
  typeof PodcastTranscriptFilteringAndSummarizationInputSchema
>;

const PodcastHighlightSchema = z.object({
  start_time: z
    .number()
    .describe(
      'Approximate start time of the highlight in seconds, relative to the beginning of the transcript. This is an estimation by the AI based on text length.'
    ),
  end_time: z
    .number()
    .describe(
      'Approximate end time of the highlight in seconds, relative to the beginning of the transcript. This is an estimation by the AI based on text length.'
    ),
  highlight_name: z.string().describe('A unique name for the highlight, e.g., "Highlight 1".'),
  hook_caption:
    z.string().max(150, 'Hook caption must be 10 words or less.')
      .describe('A 10-word or less captivating caption for the highlight.'),
});

const PodcastTranscriptFilteringAndSummarizationOutputSchema = z.object({
  summary: z
    .string()
    .describe("A summary of the podcast content that is relevant to the user's interests."),
  highlights: z
    .array(PodcastHighlightSchema)
    .describe(
      'An array of the top 5 most engaging segments from the podcast relevant to the user\'s interests, each with approximate start/end times, a name, and a short hook caption.'
    ),
});
export type PodcastTranscriptFilteringAndSummarizationOutput = z.infer<
  typeof PodcastTranscriptFilteringAndSummarizationOutputSchema
>;

export async function podcastTranscriptFilteringAndSummarization(
  input: PodcastTranscriptFilteringAndSummarizationInput
): Promise<PodcastTranscriptFilteringAndSummarizationOutput> {
  return podcastTranscriptFilteringAndSummarizationFlow(input);
}

const podcastTranscriptFilteringAndSummarizationPrompt = ai.definePrompt({
  name: 'podcastTranscriptFilteringAndSummarizationPrompt',
  input: { schema: PodcastTranscriptFilteringAndSummarizationInputSchema },
  output: { schema: PodcastTranscriptFilteringAndSummarizationOutputSchema },
  prompt: `You are an expert podcast analyst. Your task is to analyze a podcast transcript based on a user's specified interests.

First, identify all content within the transcript that is highly relevant to the provided interests.
Then, provide a concise summary of only this relevant content.
Finally, identify the top 5 most engaging and important segments from the transcript that align with the user's interests. For each identified segment, provide:
1.  An approximate \`start_time\` in seconds, estimating from the beginning of the transcript. Assume an average speaking rate of 150 words per minute for estimation, and that the transcript starts at 0 seconds.
2.  An approximate \`end_time\` in seconds, estimated similarly.
3.  A \`highlight_name\`, like "Highlight 1", "Highlight 2", etc.
4.  A compelling \`hook_caption\` that is 10 words or less, designed to entice a listener to hear that segment.

Ensure the output is a JSON object matching the specified schema, including the 'summary' and 'highlights' array. Do not include any other text outside the JSON.

User Interests:
{{#each interests}}- {{this}}
{{/each}}

Podcast Transcript:
{{{transcript}}}`,
});

const podcastTranscriptFilteringAndSummarizationFlow = ai.defineFlow(
  {
    name: 'podcastTranscriptFilteringAndSummarizationFlow',
    inputSchema: PodcastTranscriptFilteringAndSummarizationInputSchema,
    outputSchema: PodcastTranscriptFilteringAndSummarizationOutputSchema,
  },
  async (input) => {
    const { output } = await podcastTranscriptFilteringAndSummarizationPrompt(input);
    if (!output) {
      throw new Error('No output generated by the prompt.');
    }
    return output;
  }
);
